'use client';

import {
  makeDefaultParagraph,
  makeEditorValue,
  makeTable,
  makeTableCell,
  makeTableRow,
  makeText,
  makeTitleParagraph,
  makeDefaultText,
  TextStyleType,
  makeBulletListParagraph,
  ReactEditor,
  EditorValue,
  makeParagraph,
} from '@/matita';
import { useMemo, useState } from 'react';

export default function Home() {
  let id_ = 0;
  function id(): string {
    return String(id_++);
  }

  const initialValue = makeEditorValue(
    [
      makeTitleParagraph([makeDefaultText('This is the title', id())], id()),
      makeTable(
        [
          makeTableRow(
            [
              makeTableCell(
                makeEditorValue(
                  [
                    makeDefaultParagraph(
                      [
                        makeText(
                          'Song',
                          {
                            flags: TextStyleType.Bold,
                          },
                          id(),
                        ),
                      ],
                      id(),
                    ),
                  ],
                  id(),
                ),
                id(),
              ),
              makeTableCell(
                makeEditorValue(
                  [
                    makeDefaultParagraph(
                      [
                        makeText(
                          'Scrobbles',
                          {
                            flags: TextStyleType.Bold,
                          },
                          id(),
                        ),
                      ],
                      id(),
                    ),
                  ],
                  id(),
                ),
                id(),
              ),
            ],
            id(),
          ),
          makeTableRow(
            [
              makeTableCell(
                makeEditorValue(
                  [
                    makeDefaultParagraph(
                      [makeDefaultText('Nikes', id())],
                      id(),
                    ),
                  ],
                  id(),
                ),
                id(),
              ),
              makeTableCell(
                makeEditorValue(
                  [
                    makeDefaultParagraph([makeDefaultText('73', id())], id()),
                    makeTable(
                      [
                        makeTableRow(
                          [
                            makeTableCell(
                              makeEditorValue(
                                [
                                  makeDefaultParagraph(
                                    [
                                      makeText(
                                        'Song',
                                        {
                                          flags: TextStyleType.Bold,
                                        },
                                        id(),
                                      ),
                                    ],
                                    id(),
                                  ),
                                ],
                                id(),
                              ),
                              id(),
                            ),
                            makeTableCell(
                              makeEditorValue(
                                [
                                  makeDefaultParagraph(
                                    [
                                      makeText(
                                        'Scrobbles',
                                        {
                                          flags: TextStyleType.Bold,
                                        },
                                        id(),
                                      ),
                                    ],
                                    id(),
                                  ),
                                ],
                                id(),
                              ),
                              id(),
                            ),
                          ],
                          id(),
                        ),
                        makeTableRow(
                          [
                            makeTableCell(
                              makeEditorValue(
                                [
                                  makeDefaultParagraph(
                                    [makeDefaultText('Nikes', id())],
                                    id(),
                                  ),
                                  makeTable(
                                    [
                                      makeTableRow(
                                        [
                                          makeTableCell(
                                            makeEditorValue(
                                              [
                                                makeDefaultParagraph(
                                                  [
                                                    makeText(
                                                      'Song',
                                                      {
                                                        flags:
                                                          TextStyleType.Bold,
                                                      },
                                                      id(),
                                                    ),
                                                  ],
                                                  id(),
                                                ),
                                              ],
                                              id(),
                                            ),
                                            id(),
                                          ),
                                          makeTableCell(
                                            makeEditorValue(
                                              [
                                                makeDefaultParagraph(
                                                  [
                                                    makeText(
                                                      'Scrobbles',
                                                      {
                                                        flags:
                                                          TextStyleType.Bold,
                                                      },
                                                      id(),
                                                    ),
                                                  ],
                                                  id(),
                                                ),
                                              ],
                                              id(),
                                            ),
                                            id(),
                                          ),
                                        ],
                                        id(),
                                      ),
                                      makeTableRow(
                                        [
                                          makeTableCell(
                                            makeEditorValue(
                                              [
                                                makeDefaultParagraph(
                                                  [
                                                    makeDefaultText(
                                                      'Nikes',
                                                      id(),
                                                    ),
                                                  ],
                                                  id(),
                                                ),
                                              ],
                                              id(),
                                            ),
                                            id(),
                                          ),
                                          makeTableCell(
                                            makeEditorValue(
                                              [
                                                makeDefaultParagraph(
                                                  [makeDefaultText('73', id())],
                                                  id(),
                                                ),
                                              ],
                                              id(),
                                            ),
                                            id(),
                                          ),
                                        ],
                                        id(),
                                      ),
                                      makeTableRow(
                                        [
                                          makeTableCell(
                                            makeEditorValue(
                                              [
                                                makeDefaultParagraph(
                                                  [
                                                    makeDefaultText(
                                                      'Valuable Pain',
                                                      id(),
                                                    ),
                                                  ],
                                                  id(),
                                                ),
                                              ],
                                              id(),
                                            ),
                                            id(),
                                          ),
                                          makeTableCell(
                                            makeEditorValue(
                                              [
                                                makeDefaultParagraph(
                                                  [
                                                    makeDefaultText(
                                                      '223',
                                                      id(),
                                                    ),
                                                  ],
                                                  id(),
                                                ),
                                                makeDefaultParagraph(
                                                  [
                                                    makeDefaultText(
                                                      '223',
                                                      id(),
                                                    ),
                                                  ],
                                                  id(),
                                                ),
                                                makeTable(
                                                  [
                                                    makeTableRow(
                                                      [
                                                        makeTableCell(
                                                          makeEditorValue(
                                                            [
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeText(
                                                                    'Song',
                                                                    {
                                                                      flags:
                                                                        TextStyleType.Bold,
                                                                    },
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),
                                                              makeTable(
                                                                [
                                                                  makeTableRow(
                                                                    [
                                                                      makeTableCell(
                                                                        makeEditorValue(
                                                                          [
                                                                            makeDefaultParagraph(
                                                                              [
                                                                                makeText(
                                                                                  'Song',
                                                                                  {
                                                                                    flags:
                                                                                      TextStyleType.Bold,
                                                                                  },
                                                                                  id(),
                                                                                ),
                                                                              ],
                                                                              id(),
                                                                            ),
                                                                          ],
                                                                          id(),
                                                                        ),
                                                                        id(),
                                                                      ),
                                                                      makeTableCell(
                                                                        makeEditorValue(
                                                                          [
                                                                            makeDefaultParagraph(
                                                                              [
                                                                                makeText(
                                                                                  'Scrobbles',
                                                                                  {
                                                                                    flags:
                                                                                      TextStyleType.Bold,
                                                                                  },
                                                                                  id(),
                                                                                ),
                                                                              ],
                                                                              id(),
                                                                            ),
                                                                          ],
                                                                          id(),
                                                                        ),
                                                                        id(),
                                                                      ),
                                                                    ],
                                                                    id(),
                                                                  ),
                                                                  makeTableRow(
                                                                    [
                                                                      makeTableCell(
                                                                        makeEditorValue(
                                                                          [
                                                                            makeDefaultParagraph(
                                                                              [
                                                                                makeDefaultText(
                                                                                  'Nikes',
                                                                                  id(),
                                                                                ),
                                                                              ],
                                                                              id(),
                                                                            ),
                                                                          ],
                                                                          id(),
                                                                        ),
                                                                        id(),
                                                                      ),
                                                                      makeTableCell(
                                                                        makeEditorValue(
                                                                          [
                                                                            makeDefaultParagraph(
                                                                              [
                                                                                makeDefaultText(
                                                                                  '73',
                                                                                  id(),
                                                                                ),
                                                                              ],
                                                                              id(),
                                                                            ),
                                                                          ],
                                                                          id(),
                                                                        ),
                                                                        id(),
                                                                      ),
                                                                    ],
                                                                    id(),
                                                                  ),
                                                                  makeTableRow(
                                                                    [
                                                                      makeTableCell(
                                                                        makeEditorValue(
                                                                          [
                                                                            makeDefaultParagraph(
                                                                              [
                                                                                makeDefaultText(
                                                                                  'Valuable Pain',
                                                                                  id(),
                                                                                ),
                                                                              ],
                                                                              id(),
                                                                            ),
                                                                          ],
                                                                          id(),
                                                                        ),
                                                                        id(),
                                                                      ),
                                                                      makeTableCell(
                                                                        makeEditorValue(
                                                                          [
                                                                            makeDefaultParagraph(
                                                                              [
                                                                                makeDefaultText(
                                                                                  '223',
                                                                                  id(),
                                                                                ),
                                                                              ],
                                                                              id(),
                                                                            ),
                                                                          ],
                                                                          id(),
                                                                        ),
                                                                        id(),
                                                                      ),
                                                                    ],
                                                                    id(),
                                                                  ),
                                                                ],
                                                                2,
                                                                id(),
                                                              ),
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeDefaultText(
                                                                    '1',
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),

                                                              makeTable(
                                                                [
                                                                  makeTableRow(
                                                                    [
                                                                      makeTableCell(
                                                                        makeEditorValue(
                                                                          [
                                                                            makeDefaultParagraph(
                                                                              [
                                                                                makeText(
                                                                                  'Song',
                                                                                  {
                                                                                    flags:
                                                                                      TextStyleType.Bold,
                                                                                  },
                                                                                  id(),
                                                                                ),
                                                                              ],
                                                                              id(),
                                                                            ),
                                                                          ],
                                                                          id(),
                                                                        ),
                                                                        id(),
                                                                      ),
                                                                      makeTableCell(
                                                                        makeEditorValue(
                                                                          [
                                                                            makeDefaultParagraph(
                                                                              [
                                                                                makeText(
                                                                                  'Scrobbles',
                                                                                  {
                                                                                    flags:
                                                                                      TextStyleType.Bold,
                                                                                  },
                                                                                  id(),
                                                                                ),
                                                                              ],
                                                                              id(),
                                                                            ),
                                                                          ],
                                                                          id(),
                                                                        ),
                                                                        id(),
                                                                      ),
                                                                    ],
                                                                    id(),
                                                                  ),
                                                                  makeTableRow(
                                                                    [
                                                                      makeTableCell(
                                                                        makeEditorValue(
                                                                          [
                                                                            makeDefaultParagraph(
                                                                              [
                                                                                makeDefaultText(
                                                                                  'Nikes',
                                                                                  id(),
                                                                                ),
                                                                              ],
                                                                              id(),
                                                                            ),
                                                                          ],
                                                                          id(),
                                                                        ),
                                                                        id(),
                                                                      ),
                                                                      makeTableCell(
                                                                        makeEditorValue(
                                                                          [
                                                                            makeDefaultParagraph(
                                                                              [
                                                                                makeDefaultText(
                                                                                  '73',
                                                                                  id(),
                                                                                ),
                                                                              ],
                                                                              id(),
                                                                            ),
                                                                          ],
                                                                          id(),
                                                                        ),
                                                                        id(),
                                                                      ),
                                                                    ],
                                                                    id(),
                                                                  ),
                                                                  makeTableRow(
                                                                    [
                                                                      makeTableCell(
                                                                        makeEditorValue(
                                                                          [
                                                                            makeDefaultParagraph(
                                                                              [
                                                                                makeDefaultText(
                                                                                  'Valuable Pain',
                                                                                  id(),
                                                                                ),
                                                                              ],
                                                                              id(),
                                                                            ),
                                                                          ],
                                                                          id(),
                                                                        ),
                                                                        id(),
                                                                      ),
                                                                      makeTableCell(
                                                                        makeEditorValue(
                                                                          [
                                                                            makeDefaultParagraph(
                                                                              [
                                                                                makeDefaultText(
                                                                                  '223',
                                                                                  id(),
                                                                                ),
                                                                              ],
                                                                              id(),
                                                                            ),
                                                                          ],
                                                                          id(),
                                                                        ),
                                                                        id(),
                                                                      ),
                                                                    ],
                                                                    id(),
                                                                  ),
                                                                ],
                                                                2,
                                                                id(),
                                                              ),
                                                            ],
                                                            id(),
                                                          ),
                                                          id(),
                                                        ),
                                                        makeTableCell(
                                                          makeEditorValue(
                                                            [
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeText(
                                                                    'Scrobbles',
                                                                    {
                                                                      flags:
                                                                        TextStyleType.Bold,
                                                                    },
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),
                                                            ],
                                                            id(),
                                                          ),
                                                          id(),
                                                        ),
                                                      ],
                                                      id(),
                                                    ),
                                                    makeTableRow(
                                                      [
                                                        makeTableCell(
                                                          makeEditorValue(
                                                            [
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeDefaultText(
                                                                    'Nikes',
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),
                                                            ],
                                                            id(),
                                                          ),
                                                          id(),
                                                        ),
                                                        makeTableCell(
                                                          makeEditorValue(
                                                            [
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeDefaultText(
                                                                    '73',
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),
                                                            ],
                                                            id(),
                                                          ),
                                                          id(),
                                                        ),
                                                      ],
                                                      id(),
                                                    ),
                                                    makeTableRow(
                                                      [
                                                        makeTableCell(
                                                          makeEditorValue(
                                                            [
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeDefaultText(
                                                                    'Valuable Pain',
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),
                                                            ],
                                                            id(),
                                                          ),
                                                          id(),
                                                        ),
                                                        makeTableCell(
                                                          makeEditorValue(
                                                            [
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeDefaultText(
                                                                    '223',
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),
                                                            ],
                                                            id(),
                                                          ),
                                                          id(),
                                                        ),
                                                      ],
                                                      id(),
                                                    ),
                                                  ],
                                                  2,
                                                  id(),
                                                ),
                                                makeDefaultParagraph(
                                                  [makeDefaultText('1', id())],
                                                  id(),
                                                ),

                                                makeTable(
                                                  [
                                                    makeTableRow(
                                                      [
                                                        makeTableCell(
                                                          makeEditorValue(
                                                            [
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeText(
                                                                    'Song',
                                                                    {
                                                                      flags:
                                                                        TextStyleType.Bold,
                                                                    },
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),
                                                            ],
                                                            id(),
                                                          ),
                                                          id(),
                                                        ),
                                                        makeTableCell(
                                                          makeEditorValue(
                                                            [
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeText(
                                                                    'Scrobbles',
                                                                    {
                                                                      flags:
                                                                        TextStyleType.Bold,
                                                                    },
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),
                                                            ],
                                                            id(),
                                                          ),
                                                          id(),
                                                        ),
                                                      ],
                                                      id(),
                                                    ),
                                                    makeTableRow(
                                                      [
                                                        makeTableCell(
                                                          makeEditorValue(
                                                            [
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeDefaultText(
                                                                    'Nikes',
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),
                                                            ],
                                                            id(),
                                                          ),
                                                          id(),
                                                        ),
                                                        makeTableCell(
                                                          makeEditorValue(
                                                            [
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeDefaultText(
                                                                    '73',
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),
                                                            ],
                                                            id(),
                                                          ),
                                                          id(),
                                                        ),
                                                      ],
                                                      id(),
                                                    ),
                                                    makeTableRow(
                                                      [
                                                        makeTableCell(
                                                          makeEditorValue(
                                                            [
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeDefaultText(
                                                                    'Valuable Pain',
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),
                                                            ],
                                                            id(),
                                                          ),
                                                          id(),
                                                        ),
                                                        makeTableCell(
                                                          makeEditorValue(
                                                            [
                                                              makeDefaultParagraph(
                                                                [
                                                                  makeDefaultText(
                                                                    '223',
                                                                    id(),
                                                                  ),
                                                                ],
                                                                id(),
                                                              ),
                                                            ],
                                                            id(),
                                                          ),
                                                          id(),
                                                        ),
                                                      ],
                                                      id(),
                                                    ),
                                                  ],
                                                  2,
                                                  id(),
                                                ),
                                                makeDefaultParagraph(
                                                  [
                                                    makeDefaultText(
                                                      '223',
                                                      id(),
                                                    ),
                                                  ],
                                                  id(),
                                                ),
                                              ],
                                              id(),
                                            ),
                                            id(),
                                          ),
                                        ],
                                        id(),
                                      ),
                                    ],
                                    2,
                                    id(),
                                  ),
                                ],
                                id(),
                              ),
                              id(),
                            ),
                            makeTableCell(
                              makeEditorValue(
                                [
                                  makeDefaultParagraph(
                                    [makeDefaultText('73', id())],
                                    id(),
                                  ),
                                ],
                                id(),
                              ),
                              id(),
                            ),
                          ],
                          id(),
                        ),
                        makeTableRow(
                          [
                            makeTableCell(
                              makeEditorValue(
                                [
                                  makeDefaultParagraph(
                                    [makeDefaultText('Valuable Pain', id())],
                                    id(),
                                  ),
                                ],
                                id(),
                              ),
                              id(),
                            ),
                            makeTableCell(
                              makeEditorValue(
                                [
                                  makeDefaultParagraph(
                                    [makeDefaultText('223', id())],
                                    id(),
                                  ),
                                ],
                                id(),
                              ),
                              id(),
                            ),
                          ],
                          id(),
                        ),
                      ],
                      2,
                      id(),
                    ),
                  ],
                  id(),
                ),
                id(),
              ),
            ],
            id(),
          ),
          makeTableRow(
            [
              makeTableCell(
                makeEditorValue(
                  [
                    makeDefaultParagraph(
                      [makeDefaultText('Valuable Pain', id())],
                      id(),
                    ),
                  ],
                  id(),
                ),
                id(),
              ),
              makeTableCell(
                makeEditorValue(
                  [makeDefaultParagraph([makeDefaultText('223', id())], id())],
                  id(),
                ),
                id(),
              ),
            ],
            id(),
          ),
        ],
        2,
        id(),
      ),
      makeBulletListParagraph(
        [
          makeDefaultText(
            `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
            id(),
          ),
        ],
        id(),
        id(),
      ),
      makeDefaultParagraph([makeDefaultText('', id())], id()),
      makeDefaultParagraph(
        [
          makeDefaultText(
            'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
            id(),
          ),
        ],
        id(),
      ),
    ],
    id(),
  );

  return (
    <main className="markdown-body">
      <ReactEditor initialValue={initialValue} makeId={id} />
    </main>
  );
}
